# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nagarromlopsv3

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Show directory
      run: echo $PWD
    - name: Show project files
      run: ls
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: pip install -r house-prices-api/requirements.txt
    - name: Install Tox
      run: pip install tox==3.0.0
    - name: Go to project
      run: cd house-prices-api
    - name: Show project files
      run: ls
    - name: Go to project
      run: cd house-prices-api
    - name: Run Tox
      run: tox house-prices-api
    
  build:

    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image.
      run: docker build --build-arg PIP_EXTRA_INDEX_URL=https://ZzHEn6GN4KDJqpEefbKj:@pypi.fury.io/himanshuatnagarro . --file Dockerfile --tag shivdotjs/mlops:1.0.0
    - name: List docker images
      run: docker images
    - name: Login to docker hub to push image build
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push docker image updatev1
      run: docker push shivdotjs/mlops:1.0.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nagarromlopsv3'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_710346f85b2e4fd282d10f1cf7b72cc4 }}
        images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/mlops:1.0.0'
